image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/<ECR_REPO_NAME>-staging
  pullPolicy: Always
  tag: latest

fullnameOverride: "jina-reader"

externalSecrets:
  clusterSecretStoreName: asm-<REGION>
  env:
    enabled: true
    targetSecretName: jina-reader-staging
    externalEnvSecretName: jina-reader-staging
  cloudflare:
    enabled: true
    targetSecretName: jina-reader-cloudflare-tls
    externalTlsCrtSecret: cloudflare-ca-crt
    externalTlsKeySecret: cloudflare-ca-pk

envSecretName: jina-reader-staging

ingress:
  enabled: true
  className: nginx
  host: <YOUR_STAGING_HOST>
  annotations:
    nginx.ingress.kubernetes.io/send_timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    secretName: jina-reader-cloudflare-tls

crawl:
  replicaCount: 1
  args:
    - build/stand-alone/crawl.js
  extraContainerEnv:
    - name: NODE_ENV
      value: staging
  resources:
    limits:
      memory: 6Gi
    requests:
      cpu: "1"
      memory: 6Gi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80

search:
  replicaCount: 1
  args:
    - build/stand-alone/search.js
  extraContainerEnv:
    - name: NODE_ENV
      value: staging
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80

serp:
  replicaCount: 1
  args:
    - build/stand-alone/serp.js
  extraContainerEnv:
    - name: NODE_ENV
      value: staging
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
