{{- if .Values.externalSecrets.cloudflare.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.cloudflare.targetSecretName }}-es
spec:
  refreshInterval: 5h
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.cloudflare.targetSecretName }}
    creationPolicy: Owner
    template:
      data:
        tls.crt: {{ printf "'{{ .crt }}'" }}
        tls.key: {{ printf "'{{ .key }}'" }}
  data:
  - secretKey: crt
    remoteRef:
      key: {{ .Values.externalSecrets.cloudflare.externalTlsCrtSecret }}
  - secretKey: key
    remoteRef:
      key: {{ .Values.externalSecrets.cloudflare.externalTlsKeySecret }}
{{- end }}
