{{- define "jina-reader.ingressPaths" -}}
- path: /crawl(/|$)(.*)
  {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
  pathType: ImplementationSpecific
  {{- end }}
  backend:
    {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
    service:
      name: {{ include "jina-reader.componentFullname" (list . "crawl") }}
      port:
        number: 80
    {{- else }}
    serviceName: {{ include "jina-reader.componentFullname" (list . "crawl") }}
    servicePort: 80
    {{- end }}
{{- if .Values.search.enabled }}
- path: /search(/|$)(.*)
  {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
  pathType: ImplementationSpecific
  {{- end }}
  backend:
    {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
    service:
      name: {{ include "jina-reader.componentFullname" (list . "search") }}
      port:
        number: 80
    {{- else }}
    serviceName: {{ include "jina-reader.componentFullname" (list . "search") }}
    servicePort: 80
    {{- end }}
{{- end }}
{{- if .Values.serp.enabled }}
- path: /serp(/|$)(.*)
  {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
  pathType: ImplementationSpecific
  {{- end }}
  backend:
    {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
    service:
      name: {{ include "jina-reader.componentFullname" (list . "serp") }}
      port:
        number: 80
    {{- else }}
    serviceName: {{ include "jina-reader.componentFullname" (list . "serp") }}
    servicePort: 80
    {{- end }}
{{- end }}
{{- end }}
{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "jina-reader.fullname" . }}
  labels:
    {{- include "jina-reader.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.secretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- include "jina-reader.ingressPaths" . | nindent 10 }}
    {{- end }}
    {{- if .Values.ingress.internalHost }}
    - host: {{ .Values.ingress.internalHost | quote }}
      http:
        paths:
          {{- include "jina-reader.ingressPaths" . | nindent 10 }}
    {{- end }}
{{- end }}
